### ISSUE TITLE
 initialization failed: -3

### ISSUE THREAD

**Issue by VaishakC7** [tdk-invn-oss/motion.arduino.ICM42670P#7]
After connecting ICM42670P daughter board to it is now showing  initialization failed: -3. Previously the result was observed correctly.

**Comment by rbuisson-invn** [comment]
Hello Vaishak,

Could you please provide more details about your current setup and previous working one?
Result -3 means that the re is an issue in the transport.
Are you using SPI or I2C interface to communicate with the IMU?

Thanks and regards

**Comment by geekmengran** [comment]
ESP32S3 初始化失败

**Comment by geekmengran** [comment]
> 你好维沙克，
> 
> 您能否提供有关您当前设置和之前工作设置的更多详细信息？ 结果 -3 表示传输存在问题。 您使用SPI还是I2C接口与IMU通信？ 您使用哪个目标CPU？
> 
> 感谢致敬

ESP32S3初始化失败

**Comment by rbuisson-invn** [comment]
Please try new library version 1.0.1 and let us know the status.
Thanks
